### PR TITLE
Permanav

### PR DESCRIPTION
**Pull request by wheresrhys**
@adgad

### CODE REVIEW

**Comment by commuterjoy** [comment]
Assume, this works ok without JS

**Comment by wheresrhys** [comment]
yep it does (aside from mobile, but will need a proper footer for that and it's no worse than current)

**Comment by commuterjoy** [comment]
Could you duplicated this nav in the footer then and hide if user cuts the mustard and/or is on a lower viewport?

**Comment by wheresrhys** [comment]
My plan is to deprecate next-wrapper by putting remaining config stuff in next-ui-setup, scripty stuff in next-mustard and survey in a new next-footer then create the footer nav in there (needs a little bit of thought as to where to store the list of sections).
 
Gonna merge and roll out to apps asap then do it all properly next week if it proves popular.

**Comment by commuterjoy** [comment]
Mmm, just thought for the sake of 30 mins now we could knock off a missing thing.

**Comment by wheresrhys** [comment]
For now I'll give 'more' a href of '#footer-nav' that way when it does get added to the footer it'll just work without having to coordinate a new roll out of header

**Pull request merged**
