### PR TITLE
My page explanation

### PR DESCRIPTION
**Pull request by adgad**
/cc @wheresrhys 

Quite hacky but does a job
*Shows 3 times or until user explicitly presses close
screen shot 2015-03-24 at 17 16 39

### CODE REVIEW

**Comment by ironsidevsquincy** [comment]
Doesn't look hacky!

Should it be pointing to the search box?

**Comment by adgad** [comment]
No, good spot!

**Comment by commuterjoy** [comment]
Make sure you test it on a few devices please!

**Comment by adgad** [comment]
Had a look on IE9/10, Android and Safari Private browsing and it looks okay.

**Pull request merged**
